In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [45]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [46]:
# df.isnull().sum()
df = df.fillna(0)

In [47]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [48]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [49]:
y_train = df_train['fuel_efficiency_mpg']
y_val = df_val['fuel_efficiency_mpg']
y_test = df_test['fuel_efficiency_mpg']

In [50]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

In [51]:
from sklearn.feature_extraction import DictVectorizer

In [52]:
train_dicts = df_train.to_dict(orient='records')

test_dicts = df_test.to_dict(orient='records')

In [53]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [54]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_text

In [55]:
dt = DecisionTreeRegressor(max_depth=1)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [56]:
### for gettting the features used for splitting

print(export_text(dt, feature_names=list(dv.get_feature_names_out())))

|--- model_year <= 1997.50
|   |--- value: [28.61]
|--- model_year >  1997.50
|   |--- value: [31.17]

In [57]:
from sklearn.ensemble import RandomForestRegressor

In [58]:
rf = RandomForestRegressor(n_estimators=10, random_state=1, n_jobs=-1)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [59]:
val_dicts = df_val.to_dict(orient='records')
X_val = dv.transform(val_dicts)
y_pred = rf.predict(X_val)

In [60]:
from sklearn.metrics import root_mean_squared_error

In [61]:
root_mean_squared_error(y_val, y_pred)

1.8452730556749588

In [65]:
scores = []

for n in [10, 50, 100, 150]:
    rf = RandomForestRegressor(n_estimators=n, random_state=1)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_val)
    score =  root_mean_squared_error(y_val, y_pred)
    scores.append([n, round(score,3)])

In [66]:
columns = ['n', 'rmse']
scores_df = pd.DataFrame(scores, columns=columns)
scores_df

     n   rmse
0   10  1.845
1   50  1.773
2  100  1.769
3  150  1.768

In [73]:
scores = []

for d in [10, 15, 20, 25]:
    for n in [10, 50, 100, 150]:
        rf = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=1, n_jobs=-1)
        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_val)
        score = root_mean_squared_error(y_val, y_pred)
        scores.append([n, d, score])

In [74]:
columns = ['n_estimators', 'max_depth', 'rmse']
scores_df = pd.DataFrame(scores, columns=columns)
max_depth_group = scores_df.groupby('max_depth').mean()
round(max_depth_group,3)

           n_estimators   rmse
max_depth
10                 77.5  1.756
15                 77.5  1.782
20                 77.5  1.790
25                 77.5  1.787

In [75]:
rf = RandomForestRegressor(n_estimators=10, max_depth=20, random_state=1, n_jobs=-1)
rf.fit(X_train, y_train)
rf.feature_importances_

array([0.05576989, 0.00772938, 0.02013006, 0.00564178, 0.06121405,
       0.0200582 , 0.16071252, 0.01280898, 0.07804943, 0.29598807,
       0.0073298 , 0.01946819, 0.00631509, 0.00373047, 0.04219035,
       0.20286376])

In [86]:
importance_df = pd.DataFrame({
    'feature': dv.get_feature_names_out(),
    'importance': rf.feature_importances_
}
)

importance_df = importance_df.sort_values(by='importance', ascending=False).reset_index(drop=True)

In [87]:
importance_df

                         feature  importance
0                     model_year    0.295988
1                 vehicle_weight    0.202864
2             fuel_type=Gasoline    0.160713
3                     horsepower    0.078049
4            engine_displacement    0.061214
5                   acceleration    0.055770
6                     origin=USA    0.042190
7   drivetrain=Front-wheel drive    0.020130
8               fuel_type=Diesel    0.020058
9                      num_doors    0.019468
10              fuel_type=Hybrid    0.012809
11    drivetrain=All-wheel drive    0.007729
12                 num_cylinders    0.007330
13                   origin=Asia    0.006315
14   drivetrain=Rear-wheel drive    0.005642
15                 origin=Europe    0.003730

In [90]:
%pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /Users/apple/Library/Python/3.11/lib/python/site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in /Users/apple/Library/Python/3.11/lib/python/site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 9.4 MB/s  0:00:00 eta 0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 26.1 -> 26.2.2
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [91]:
import xgboost as xgb

In [92]:
features = list(dv.get_feature_names_out())
dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=features)
dval = xgb.DMatrix(X_val, label=y_val, feature_names=features)

In [94]:
xgb_params = {
    'eta': 0.3,
    'max_depth': 6,
    'min_child_weight': 1,

    'objective': 'reg:squarederror', 
    'nthread': 8,

    'seed':1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100)
y_pred = model.predict(dval)
root_mean_squared_error(y_pred, y_val)

1.8264579799904583

In [95]:
xgb_params = {
    'eta': 0.1,
    'max_depth': 6,
    'min_child_weight': 1,

    'objective': 'reg:squarederror', 
    'nthread': 8,

    'seed':1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100)
y_pred = model.predict(dval)
root_mean_squared_error(y_pred, y_val)

1.724810059827976